<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_DC</name>
   <tag></tag>
   <elementGuidId>a4a9e17e-bdf1-46d6-b5d1-5bae24f8b0b8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/div[@class=&quot;ContentContainer Dashboard&quot;]/div[@class=&quot;Content&quot;]/article[@class=&quot;Page Dashboard&quot;]/div[@class=&quot;PageContainer&quot;]/h2[1]</value>
   </webElementProperties>
</WebElementEntity>
