<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Permission</name>
   <tag></tag>
   <elementGuidId>97ffdd6e-20dd-426b-8c79-548c86eed5d5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permission</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/div[@class=&quot;ContentContainer Dashboard&quot;]/div[@class=&quot;Content&quot;]/article[@class=&quot;Page Dashboard&quot;]/div[@class=&quot;PageContainer&quot;]/h2[1]</value>
   </webElementProperties>
</WebElementEntity>
